-- 코드를 입력하세요
SELECT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
ON A.CAR_ID = B.CAR_ID
WHERE B.CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR 
    WHERE CAR_TYPE = "세단"
) AND MONTH(B.START_DATE) = 10
GROUP BY B.CAR_ID
ORDER BY B.CAR_ID DESC